name: Build and Notify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image to Docker Registry
      run: |
        docker buildx create --use --platform linux/amd64,linux/arm64 --name multi-platform-builder
        docker buildx inspect --bootstrap
        docker buildx build --platform linux/amd64,linux/arm64 --pull --push -t ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest -f ./Dockerfile .
      env:
        DOCKER_CLI_AARCH64: 1

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest
